### ISSUE TITLE
An exemple

### ISSUE THREAD

**Issue by mickaelw** [ioddly/react-native-vector-icons-ts#1]
Do you have an exemple to use your definition?

**Comment by ioddly** [comment]
Yeah, it's right at the top of the file

https://github.com/ioddly/react-native-vector-icons-ts/blob/master/index.d.ts

I only added FontAwesome and IonIcons before I stopped

**Comment by mickaelw** [comment]
Yes I saw your example but if I strictly use it I have a compilation error : "Cann't find module ..". I make a gist with my code https://gist.github.com/mickaelw/4eec172491c710d074f7743e8f3ec435.

I already use another definitions before they worked. Your code is little different. If you can help me.
